apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iotdemo

resources:
- iotdemo-namespace.yaml
- iotdemo-operatorgroup.yaml
- rolebinding-system-imagepullers.yaml

bases:
- ../manuela-team-rolebindings
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/amq?ref=manuela-1.1
# Open data hub is optional
#- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/opendatahub?ref=manuela-1.1




