apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iotdemo

resources:
- iotdemo-namespace.yaml
- iotdemo-operatorgroup.yaml
- rolebinding-system-imagepullers.yaml

bases:
- ../manuela-team-rolebindings
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/amq?ref=master
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/seldon?ref=master
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/amq-streams?ref=master
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/camel-k?ref=master
- ../../jobs/installplan-approver


# Open data hub is optional
# if included here, the install will fail because kustomize will change the namespace from openshift-operators to iotdemo
#- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/opendatahub?ref=master




