apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-ml-workspace

bases:
- ../manuela-team-rolebindings
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/opendatahub?ref=manuela-1.1

resources:
- manuela-ml-workspace-namespace.yaml
- manuela-ml-workspace-operatorgroup.yaml
