apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/opendatahub?ref=manuela-1.3

patchesStrategicMerge:
- opendatahub-subscription.yaml