apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-temp-amq

resources:
- manuela-temp-amq-namespace.yaml
- manuela-temp-amq-operatorgroup.yaml
- ../../jobs/installplan-approver


bases:
- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/amq?ref=master
